### PR TITLE
Resolves #6 Coin Operated Doors

### LINKED ISSUE #6: Coin Operated Doors
**Requirements**
N/A

**As a** Player
**I want** Coin Operated Doors
**So that** coins I collect unlock new areas 

**Acceptance Criteria**

- Doors have 2 notables states, opened and closed. 
- Initial state is closed.
- A number representing the amount of coins required is determined on a per-door basis
- When the player is within a predetermined distance of a door, that door's required coin amount should appear drawn on the GUI layer at the door's onscreen position, regardless of whether it is open or closed.
- When the number of coins reaches the predetermined requirement, the door will open upon collision with the player.
- The door opens by rotating clockwise 90 degrees. It's origin of rotation rests in the right side of the door as the player is facing it. This ensures the door will always open inward, and away from the player. 
- As there are no known recorded events of this happening in the wild, pictures provided are merely an artist's interpretation of the phenomenon. 

image

### PR DESCRIPTION
**Pull request by johnying7**
Resolves #6 Coin Operated Doors

Use one Coin Manager prefab PER SCENE.
Use as many doors as you wish.

Game Designer Notes: set the coin requirement in the inspector to have different amounts required to open the doors by.

### CODE REVIEW

**Comment by johnying7** [comment]
@taggartdev

**Review by taggartdev — CHANGES_REQUESTED** [review]
@johnying7 

The Door Controller Script isn't an added component of the Door's Prefab, as it is in the Door placed in the Door Test Scene, but probably should be, right?

The text is improperly rendered for the new camera. Because the final camera angle may change, I will fix this after the coins are fully implemented and I am building a level. 

The door controller doesn't seem to be working properly. Changing the value of **Current Coins Collected** to something higher than the Door Controller's **Coins Required** doesn't affect the value of **Requirements Satisfied** Whether the Door opens to the Cube in this instance seems to rely solely on whether Requirements Satisfied is set to be true manually, whether the Current Coins Collected is higher or lower than necessary.

If the door is working as intended, you may need to explain the steps needed to reproduce the intended outcome, I could be using the door improperly.

**Comment by johnying7** [comment]
Good catch. Yeah, it should be part of the prefab. I'll fix that.

I wasn't sure which best fit the situation since there were some things with the camera that we needed to figure out, but I figured I could easily set it up so that all you would have to do is change the scaling and sizes to match a top-down view if you needed.

As it's set, I designed it that way in relation to the other methods. Manually setting it in the editor won't be the end-result because the unfinished issue will change how it actually works because it will be integrated. The idea is that if every time the player collects a coin (let's say the requirement is 1 coin to open the first door), collected coin 2,3,4,5,etc. will all call that same bit of code to allocate requirements satisfied (when it actually only changes in one case). Let's say the level has 500 doors and 499 of them have been unlocked. If I set it to be greater than the requirement, it will still run that code when it doesn't need to, bogging down resources. If there is an instance where more than one coin will be incremented at a time (such as a fat coin or dollar bill, increasing coin amount by 5), it would make sense to change it to greater than the amount and check for the additional case. That wasn't stated so I don't expect the amount to be increased by more than 1 per frame.

I can go back over the code to double check and make sure it's properly efficient.

**Comment by taggartdev** [comment]
Everything seems to work as intended!

**Review by taggartdev — APPROVED** [review]
This should fix the pull request!

**Pull request merged**
